---
label: Product
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: This is the product title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Description
- name: featured_image
  type: file
  config:
    maxSize: 1
  label: Featured Image
pages:
- tiitllelele.md
